const countries = {
    "ar-SA": "Arabic",
    "bn-IN": "Bengali",
    "en-GB": "English",
    "fr-FR": "French",
    "de-DE": "German",
    "el-GR": "Greek",
    "gu-IN": "Gujarati",
    "hi-IN": "Hindi",
    "it-IT": "Italian",
    "ja-JP": "Japanese",
    "kn-IN": "Kannada",
    "ko-KR": "Korean",
    "la-VA": "Latin",
    "pa-IN": "Punjabi",
    "ru-RU": "Russian",
    "es-ES": "Spanish",
    "ta-LK": "Tamil",
    "te-IN": "Telugu",
}