var msg1 =document.getElementById("message1");
var msg2 =document.getElementById("message2");
var msg3 =document.getElementById("message3");
document.getElementById("my_btn").addEventListener("click",play);

var answer = Math.floor(Math.random()*20)+1;
var no_of_guesses=0;
var guessed_nums=[];

function play(){ 
    //The value of the input box is stored in a constant called 'user guess'.
       var user_guess = document.getElementById("guess").value;
    //When your input number is less than 1 and more than 15 then you can see the following text
       if(user_guess < 1 || user_guess > 20){
           alert("Please enter a number between 1 and 15.");
       }
    //The following conditions will work when your input number is between 1 and 15
       else{
           guessed_nums.push(user_guess);
           no_of_guesses+= 1;
    //When the random number generated by the game is less than the user's input number, then the following text can be seen.
           if(user_guess < answer){
              msg1.textContent = "Your guess is too low.😪";
              msg2.textContent = "No. of guesses: " + no_of_guesses;
              msg3.textContent = "Guessed numbers are: " +
                guessed_nums;
           }
    //When the random number generated by the game exceeds the user's input number, the following text can be seen.
           else if(user_guess > answer){
              msg1.textContent = "Your guess is too high.😲";
              msg2.textContent = "No. of guesses: " + no_of_guesses;
              msg3.textContent = "Guessed numbers are: " +
                 guessed_nums;
           }
    //When the random number generated by the game and the user's input number are the same then the following text can be seen.
           else if(user_guess == answer){
              msg1.textContent = "Yippie You Win!!😍😍";
              msg2.textContent = "The number was: " + answer;
              msg3.textContent = "You guessed it in "+ no_of_guesses + " guesses";
              document.getElementById("my_btn").disabled = true;
           }
        }
     }